//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrition
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> QuantityOfProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
