//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Nutrition = new HashSet<Nutrition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Calories { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Fats { get; set; }
        public Nullable<double> Carbohydrates { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nutrition> Nutrition { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
