//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Nutrition = new HashSet<Nutrition>();
            this.WaterIntake = new HashSet<WaterIntake>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<double> Mass { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> LifestyleId { get; set; }
        public Nullable<int> PurposeId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Lifestyle Lifestyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nutrition> Nutrition { get; set; }
        public virtual Purpose Purpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaterIntake> WaterIntake { get; set; }
    }
}
